version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./sql/postgres/schema.sql:/docker-entrypoint-initdb.d/create.sql
      - ./sql/postgres/data.sql:/docker-entrypoint-initdb.d/data.sql
      - ./.postgres-data:/var/lib/postgresql/data
    networks:
      postgres-local-network: { }

  mysql-server:
    image: mysql:latest
    container_name: mysql-server
    volumes:
      - ./sql/mysql/schema.sql:/docker-entrypoint-initdb.d/create.sql
      - ./sql/mysql/data.sql:/docker-entrypoint-initdb.d/data.sql
      - "./.mysql-data/db:/var/lib/mysql"
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "Seeddb"
      # MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    networks:
      mysql-local-network: { }

networks:
  postgres-local-network:
    name: postgres-local-network
    driver: bridge
  mysql-local-network:
    name: mysql-local-network
    driver: bridge
